### ISSUE TITLE
RuntimeError: timer <frame object at 0x7f89e3a9eb30><posix.stat>: .stop() has not been called

### ISSUE THREAD

**Issue by romainrichard** [RussellLuo/pyprof-timer#1]
Hi,

I wanted to try this library so I followed the example in the README and add the following to my code:
```
from pyprof_timer import Profiler, Tree


def show(p):
    print(Tree(p.root))
 
 
@Profiler(on_disable=show)
def run():
    # my code
```

I tried to run my script a few times but always got the same error:
```
Traceback (most recent call last):
  File "save_unread.py", line 94, in <module>
    run()
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/pyprof_timer/profiler.py", line 212, in decorator
    self.disable()
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/pyprof_timer/profiler.py", line 151, in disable
    self._on_disable_callback(self)
  File "save_unread.py", line 60, in show
    print(Tree(p.root))
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/six.py", line 842, in <lambda>
    klass.__str__ = lambda self: self.__unicode__().encode('utf-8')
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/pyprof_timer/tree.py", line 32, in __str__
    self.nodes, format_node=itemgetter(0), get_children=itemgetter(1)
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/pyprof_timer/tree.py", line 27, in nodes
    for child in self._timer.children]
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/pyprof_timer/tree.py", line 27, in nodes
    for child in self._timer.children]
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/pyprof_timer/tree.py", line 27, in nodes
    for child in self._timer.children]
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/pyprof_timer/tree.py", line 27, in nodes
    for child in self._timer.children]
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/pyprof_timer/tree.py", line 27, in nodes
    for child in self._timer.children]
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/pyprof_timer/tree.py", line 27, in nodes
    for child in self._timer.children]
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/pyprof_timer/tree.py", line 27, in nodes
    for child in self._timer.children]
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/pyprof_timer/tree.py", line 27, in nodes
    for child in self._timer.children]
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/pyprof_timer/tree.py", line 27, in nodes
    for child in self._timer.children]
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/pyprof_timer/tree.py", line 24, in nodes
    span = self._span_fmt % self._timer.span(self._span_unit)
  File "/home/romain/.virtualenvs/Feedly/local/lib/python2.7/site-packages/pyprof_timer/timer.py", line 186, in span
    raise RuntimeError('timer %s: .stop() has not been called' % self._name)
RuntimeError: timer <frame object at 0x7fdf91925b30><posix.stat>: .stop() has not been called
```

Any idea what could be happening? Any more data you need from me?

**Comment by RussellLuo** [comment]
Probably there's an exception related to `os.stat()` in your code.

You can expose this exception by doing the following change:

```python
@Profiler(on_disable=show)
def run():
    # my code
```

to:

```python
@Profiler()
def run():
    # my code
```

Obviously `pyprof_timer` didn't handle this case properly, I'll try to fix this bug later.

**Comment by romainrichard** [comment]
When I do it that way, the script finishes without showing anything (which I guess makes sense since now we didn't tell it to call `show`). No exception gets raised, the script just exits normally.

**Comment by RussellLuo** [comment]
Maybe the full code can help me debug the problem, if you don't mind :)

**Comment by romainrichard** [comment]
Looks like `pyprof-timer` doesn't play well with `requests`. I was able to minimize my code and I'm still getting the error with the following:
```
from pyprof_timer import Profiler, Tree
import requests


def show(p):
    print(Tree(p.root))


@Profiler(on_disable=show)
def run():
    requests.get("http://www.google.com")


if __name__ == "__main__":
    run()
```

**Comment by RussellLuo** [comment]
While debugging in depth, I found `os.stat` does raise an exception (which will affect the behaviour of `sys.setprofile` in `pyprof-timer`):

```
(('/Users/russellluo/Projects/personal/pyprof-timer/venv/lib/python2.7/genericpath.py', 23, 'exists'), u'<posix.stat>', 'c_call', <built-in function stat>)
(('/Users/russellluo/Projects/personal/pyprof-timer/venv/lib/python2.7/genericpath.py', 23, 'exists'), u'exists  [/Users/russellluo/Projects/personal/pyprof-timer/venv/lib/python2.7/genericpath.py:23]', 'c_exception', <built-in function stat>)
```

but the above exception has been catched by `exists` at "/Users/russellluo/Projects/personal/pyprof-timer/venv/lib/python2.7/genericpath.py:23":

```python
 21 # Does a path exist?
 22 # This is false for dangling symbolic links on systems that support them.
 23 def exists(path):
 24     """Test whether a path exists.  Returns False for broken symbolic links"""
 25     try:
 26         os.stat(path)
 27     except os.error:
 28         return False
 29     return True
```

then the script, on the face of it, will exit normally.

**Comment by RussellLuo** [comment]
The problem has been fixed, you can have a try by installing the new development version:

```
$ pip install -e git+https://github.com/RussellLuo/pyprof-timer.git#egg=pyprof-timer
```

Then you will see the profiling result (but with a lot of noise), you can set the `depth` to just see several levels starting from `run()`:

```python
@Profiler(depth=2, on_disable=show)
def run():
    requests.get("http://www.google.com")
```

**Comment by romainrichard** [comment]
Perfect! Thanks for the fix and the speed!
